# Generated by Django 5.2.8 on 2025-11-23 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioParqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('CARRO', 'CARRO'), ('MOTO', 'MOTO'), ('DISCAPACIDAD', 'DISCAPACIDAD')], max_length=20)),
                ('estado', models.CharField(choices=[('LIBRE', 'LIBRE'), ('RESERVADO', 'RESERVADO'), ('OCUPADO', 'OCUPADO'), ('BLOQUEADO', 'BLOQUEADO')], default='LIBRE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SIN_RESERVA', 'SIN_RESERVA'), ('DANIO_ESPACIO', 'DANIO_ESPACIO'), ('OCUPACION_INDEBIDA', 'OCUPACION_INDEBIDA'), ('OTRO', 'OTRO')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.espacioparqueadero')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_vehiculo', models.CharField(choices=[('CARRO', 'CARRO'), ('MOTO', 'MOTO')], max_length=10)),
                ('placa', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('RESERVADA', 'RESERVADA'), ('CANCELADA', 'CANCELADA'), ('COMPLETADA', 'COMPLETADA'), ('VENCIDA', 'VENCIDA')], default='RESERVADA', max_length=20)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.espacioparqueadero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
